### ISSUE TITLE
Fix 1

### ISSUE THREAD

**Issue by oleksiykalashnyk** [MrBerebesh/learnFlex1#1]
Look at the mistake

https://github.com/MrBerebesh/learnFlex1/blob/07d58a42c92e882182e66cfdf555d39b1260178d/index.html#L8

**Comment by oleksiykalashnyk** [comment]
### W8 you fix on  [branch](/MrBerebesh/learnFlex1/tree/media)

**Comment by MrBerebesh** [comment]
i change way for style.css, itrs right?
